# Generated by Django 2.1 on 2018-10-02 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('url', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('follower_count', models.IntegerField(default=0)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=11)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('minute_length', models.IntegerField(default=0)),
                ('second_length', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SamplePack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('purchase_count', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('num_samples', models.IntegerField(default=0)),
                ('buyers', models.ManyToManyField(blank=True, related_name='buyers_set', to='microservices.Musician')),
                ('current_seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_set', to='microservices.Musician')),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='microservices.SamplePack'),
        ),
    ]
