# Generated by Django 2.1 on 2018-10-25 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplepack',
            name='current_seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='microservices.Musician'),
        ),
    ]
