# Generated by Django 2.1 on 2018-10-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservices', '0002_auto_20181025_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authenticator',
            fields=[
                ('user_id', models.CharField(max_length=25)),
                ('authenticator', models.IntegerField(primary_key=True, serialize=False)),
                ('date_created', models.DateField()),
            ],
        ),
    ]
