# Generated by Django 2.1 on 2018-11-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservices', '0004_auto_20181114_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticator',
            name='authenticator',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
