# Generated by Django 2.1 on 2018-11-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservices', '0005_auto_20181118_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticator',
            name='authenticator',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='authenticator',
            name='user_id',
            field=models.IntegerField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
