# Generated by Django 2.1 on 2018-11-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservices', '0008_auto_20181118_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
