# Generated by Django 2.1 on 2018-11-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservices', '0009_auto_20181120_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
