# Generated by Django 2.1 on 2018-12-16 23:12

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('microservices', '0010_auto_20181121_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('item_id', models.OneToOneField(primary_key=True, serialize=False, on_delete=django.db.models.deletion.CASCADE, to='microservices.SamplePack')),
                ('recommended', models.ManyToManyField(blank=True, related_name='recommended_items', to='microservices.SamplePack')),
            ],
        ),
    ]
