# Generated by Django 2.1 on 2018-12-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservices', '0010_auto_20181121_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50)),
                ('recommended', models.ManyToManyField(blank=True, related_name='recommended_items', to='microservices.SamplePack')),
            ],
        ),
    ]
